version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-deps-{{ checksum "yarn.lock" }}
            - v3-deps-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: v3-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache

      - run:
          name: Typescript Check
          command: yarn tsc --noEmit
